- Hero6.sln
> Changed name of Solution Folder "Solution Items" to ".paket"

- .editorconfig
Added some comments to .editorconfig to explain what file types the file extensions were referring to
> Added some comments to .editorconfig

- src/AdventureGame/UI/UserInterface.cs
- src/Hero6.UserInterface.SierraVGA/SierraVGAController.cs
- src/Hero6/Game.cs
- src/Hero6/Input/InputHandler.cs
- src/Hero6/Input/Mouse/MouseHandler.cs
- src/Hero6/UserInterface/UserInterfaceHandler.cs
> Rewrote the UI to have dynamic assignment of UI size and scale

- src/Hero6.UserInterface.SierraVGA/SierraVGAController.cs
- src/Hero6.UserInterface.SierraVGA/View/RootView.xaml
Enabled text wrapping and dimensions of text box is calculated  dynamically
> Fixed text in Text Box going over multiple lines

- assets/Hero6.Content.mgcb
- assets/Sprites/GUIs/Cursors/Arrow.png
- src/Hero6.UserInterface.SierraVGA/Hero6.UserInterface.SierraVGA.csproj
- src/Hero6.UserInterface.SierraVGA/MouseCursor.cs
- src/Hero6.UserInterface.SierraVGA/SierraVGAController.cs
- src/Hero6/Input/InputHandler.cs
- src/Hero6/Input/Mouse/MouseHandler.cs
> Mouse cursor rendering correctly

- src/Hero6.Installer.Windows/Product.wxs
Updated installer to work with the most recent directories
> Updated installer

- .editorconfig
- docs/LICENSE.THIRDPARTY.md
Like the title says, I also added markdown syntax files to editorconfig
> Included physical copies of third party licenses

- assets/Backgrounds/Albion/FountainRegions.png
- assets/Backgrounds/Albion/HillOverAlbionRegions.png
- src/AdventureGame/AdventureGame.csproj
- src/AdventureGame/Campaign.cs
- src/AdventureGame/Game/AdventureGameElement.cs
- src/AdventureGame/Game/Character.cs
- src/AdventureGame/Game/CharacterAnimation.cs
- src/AdventureGame/Game/Hotspot.cs
- src/AdventureGame/Game/Interaction.cs
- src/AdventureGame/Game/InventoryItem.cs
- src/AdventureGame/Game/Item.cs
- src/AdventureGame/Game/Room.cs
- src/AdventureGame/UI/UserInteractionEventArgs.cs
- src/Hero6.Campaigns.RitesOfPassage/Characters/Hero.cs
- src/Hero6.Campaigns.RitesOfPassage/Characters/Llewella.cs
- src/Hero6.Campaigns.RitesOfPassage/Items/BentSword.cs
- src/Hero6.Campaigns.RitesOfPassage/Rooms/Albion/Fountain.cs
- src/Hero6.Campaigns.RitesOfPassage/Rooms/Albion/HillOverAlbion.cs
- src/Hero6.UserInterface.SierraVga/SierraVgaController.cs
- src/Hero6.UserInterface.SierraVga/ViewModel/RootViewModel.cs
The player can now walk, look, grab and talk appropriately with characters, items and hotspots in a room.
> Added full support for Sierra VGA verbs

- src/Hero6.UserInterface.SierraVga/SierraVgaController.cs
- src/Hero6.UserInterface.SierraVga/ViewModel/RootViewModel.cs
- Mouse cursor wil default to walk on scroll wheel click
- Right mouse button will cycle verb cursors
> #87 #89 Scroll wheel click and right mouse button click

- src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
Resubmitting PR #99 after the last force push
> Add AutoGenerateBindingRedirect to DesktopGL

- src/Hero6/Utilities/DummyLogger.cs
All funcitons must be placed after properties
> Stylecop fix

- src/AdventureGame/Properties/AssemblyInfo.cs
- src/Collections/Properties/AssemblyInfo.cs
- src/Hero6.Android/Properties/AndroidManifest.xml
- src/Hero6.Campaigns.RitesOfPassage/Properties/AssemblyInfo.cs
- src/Hero6.UserInterface.SierraVga.Xaml/Properties/AssemblyInfo.cs
- src/Hero6.UserInterface.SierraVga/Properties/AssemblyInfo.cs
- src/Search/Properties/AssemblyInfo.cs
> Update versions to v0.1.0

- src/Hero6.UserInterface.SierraVga/Entities/Padding.cs
- src/Hero6.UserInterface.SierraVga/Hero6.UserInterface.SierraVga.csproj
- src/Hero6.UserInterface.SierraVga/ViewModel/TextBoxViewModel.cs
My attempt at formal text box implementation focused on the occasional
collision of font pixels and textbox boundary.  The solution was to
introduce padding with a minimum padding of 1f.
> Adding padding entity and alternate textbox

- src/AdventureGame.Tests/AdventureGame.Tests.csproj
- src/AdventureGame/AdventureGame.csproj
- src/Collections.Tests/Collections.Tests.csproj
- src/Collections/Collections.csproj
- src/Hero6.Campaigns.RitesOfPassage/Hero6.Campaigns.RitesOfPassage.csproj
- src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
- src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
- src/Hero6.UserInterface.SierraVga.Xaml/Hero6.UserInterface.SierraVga.Xaml.csproj
- src/Hero6.UserInterface.SierraVga/Hero6.UserInterface.SierraVga.csproj
- src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj
- src/Hero6.WindowsDX/Hero6.WindowsDX.csproj
- src/Search.Tests/Search.Tests.csproj
- src/Search/Search.csproj
It should now be supported on multiple platforms
> Updated .NET version to v4.6.1

- src/AdventureGame.Tests/AdventureGame.Tests.csproj
- src/AdventureGame.Tests/Engine/Graphics/MockGraphicsHandler.cs
- src/AdventureGame.Tests/GameLoop/DrawEventArgsTests.cs
- src/AdventureGame.Tests/GameLoop/LoadEventArgsTests.cs
- src/AdventureGame.Tests/GameLoop/UnloadEventArgsTests.cs
- src/AdventureGame.Tests/GameLoop/UpdateEventArgsTests.cs
- src/AdventureGame/AdventureGame.csproj
- src/AdventureGame/Campaign.cs
- src/AdventureGame/Game/AdventureGameElement.cs
- src/AdventureGame/Game/Character.cs
- src/AdventureGame/Game/CharacterAnimation.cs
- src/AdventureGame/Game/InventoryItem.cs
- src/AdventureGame/Game/Item.cs
- src/AdventureGame/Game/Room.cs
- src/AdventureGame/Game/SpriteSheet.cs
- src/AdventureGame/GameLoop/DrawEventArgs.cs
- src/AdventureGame/GameLoop/IGameLoop.cs
- src/AdventureGame/GameLoop/LoadEventArgs.cs
- src/AdventureGame/GameLoop/UnloadEventArgs.cs
- src/AdventureGame/GameLoop/UpdateEventArgs.cs
- src/AdventureGame/UI/UserInterface.cs
- src/Hero6.UserInterface.SierraVga/MouseCursor.cs
- src/Hero6.UserInterface.SierraVga/SierraVgaController.cs
I added some features to the game loop which was needed for some experimental work I'm doing.
> Game Loop added features

- src/build.bat
VSTS didn't like them, they're kinda unnecessary either way.
> Removed comments from build batch script

- README.md
Commented lines wasn't appreciated by GitHub for some reason, we don't really need to keep this information in the README either way, it's just as easy to create it from scratch when we eventually need it.
> Fixed broken rendering in README

- src/Collections.Tests/Collections.Tests.csproj
- src/Collections/Collections.csproj
- src/Hero6.Android/Hero6.Android.csproj
- src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
- src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
- src/Hero6.Engine.Campaigns.RitesOfPassage/Hero6.Engine.Campaigns.RitesOfPassage.csproj
- src/Hero6.Engine.Tests/Hero6.Engine.Tests.csproj
- src/Hero6.Engine.UserInterfaces.SierraVga.Xaml/Hero6.Engine.UserInterfaces.SierraVga.Xaml.csproj
- src/Hero6.Engine.UserInterfaces.SierraVga/Hero6.Engine.UserInterfaces.SierraVga.csproj
- src/Hero6.Engine/Hero6.Engine.csproj
- src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj
- src/Hero6.WindowsDX/Hero6.WindowsDX.csproj
- src/Search.Tests/Search.Tests.csproj
- src/Search/Search.csproj
This property was missing for most projects Release builds
> Treat warnings as errors hotfix

- src/Hero6/Game.cs
I made GraphicsDeviceManager into a public static property for easy global access. I think this is fair to do since it's essentially a controller to the GPU hardware and therefore it doesn't need to be bound by any OOP paradigms.
> Global Graphics Device Manager

- src/Collections.Tests/Collections.Tests.csproj
- src/Collections/Collections.csproj
- src/Hero6.Android/Hero6.Android.csproj
- src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
- src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
- src/Hero6.Engine.Campaigns.RitesOfPassage/Hero6.Engine.Campaigns.RitesOfPassage.csproj
- src/Hero6.Engine.Tests/Hero6.Engine.Tests.csproj
- src/Hero6.Engine.UserInterfaces.SierraVga.Xaml/Hero6.Engine.UserInterfaces.SierraVga.Xaml.csproj
- src/Hero6.Engine.UserInterfaces.SierraVga/Hero6.Engine.UserInterfaces.SierraVga.csproj
- src/Hero6.Engine/Hero6.Engine.csproj
- src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj
- src/Hero6.WindowsDX/Hero6.WindowsDX.csproj
- src/Search.Tests/Search.Tests.csproj
- src/Search/Search.csproj
Combined with StyleCop it was just too relentless
> Disabled treat warning as error

- src/paket.dependencies
- src/paket.lock
Apperantly VSTS needs this to run unit tests
> Added NUnit 3 Test Adapter package

- src/Hero6.Engine/UserInterfaces/Input/Mouse.cs
> Mouse rendering at last known location when out of game window

- assets/Gui/Sierra Vga/Extension Bar/Left.png
- assets/Gui/Sierra Vga/Extension Bar/Right.png
- assets/Gui/Sierra Vga/Extension Bar/Run.png
- assets/Gui/Sierra Vga/Extension Bar/Sleep.png
- assets/Gui/Sierra Vga/Extension Bar/Sneak.png
- assets/Gui/Sierra Vga/Extension Bar/Stats.png
- assets/Gui/Sierra Vga/Extension Bar/Time.png
- assets/Hero6.Content.mgcb
- src/Hero6.Engine.UserInterfaces.SierraVga/Dialogs/ExtensionBar.cs
- src/Hero6.Engine.UserInterfaces.SierraVga/Hero6.Engine.UserInterfaces.SierraVga.csproj
- src/Hero6.Engine.UserInterfaces.SierraVga/SierraVgaController.cs
- src/Hero6.Engine.UserInterfaces.SierraVga/Windows/VerbBar.cs
- src/Hero6.Engine/UserInterfaces/Controls/StackPanel.cs
- src/Hero6.Engine/UserInterfaces/Controls/UserInterfaceElement.cs
- src/Hero6.Engine/UserInterfaces/Input/Mouse.cs
- src/Hero6.Engine/UserInterfaces/UserInterface.cs
> Added extension bar and some bug fixes

- README.md
- src/Hero6.Installer.Windows/Hero6.Installer.Windows.aip
- Updated minimum required OS in Readme. Fixes #180
- Updated minimum required .net framework in readme and Windows Installer. Fixes #179
> Updated system requirements

- assets/Gui/Sierra Vga/Extension Bar/Run.png
- assets/Gui/Sierra Vga/Extension Bar/Sleep.png
- assets/Gui/Sierra Vga/Extension Bar/Sneak.png
- assets/Gui/Sierra Vga/Extension Bar/Stats.png
- assets/Gui/Sierra Vga/Extension Bar/Time.png
For some reason when GitHub merged Pull Request #190 renamed files became added files instead.
> Removed textures that are no longer needed

- src/Hero6.Engine/Campaigns/AdventureGameElement.cs
- src/Hero6.Engine/Campaigns/Character.cs
- src/Hero6.Engine/Campaigns/CharacterAnimation.cs
- src/Hero6.Engine/Campaigns/InventoryItem.cs
- src/Hero6.Engine/Campaigns/Item.cs
- src/Hero6.Engine/Campaigns/Room.cs
Made events for load, unload, update and draw to be invoked from with the AdventureGameElement class, instead of each class inheriting from AdventureGameElement having to invoke the events.
> Moved invokation of AdventureGameElement events

- .editorconfig
Added new properties recently introduced by Microsoft and JetbBrains to take advantage of EditorConfig and make sure we have consistent code style and formatting across various text editors
> Added EditorConfig C#, .NET and Resharper properties

- src/build.fsx
Tests weren't running because of directory error
> Fixed error in FAKE script

- src/.paket/paket.exe
- src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
- src/Hero6.DesktopGL.Tests/paket.references
- src/Hero6.DesktopGL/App.config
- src/Hero6.DesktopGL/Properties/Settings.Designer.cs
- src/Hero6.DesktopGL/Properties/Settings.settings
- src/Hero6.Engine/Utilities/DependencyInjection/IServices.cs
- src/Hero6.Engine/Utilities/Settings/IUserSettings.cs
- src/Hero6.Tests/Engine/Utilities/DependencyInjection/ServicesTests.cs
- src/Hero6.Tests/Engine/Utilities/Logger/LogFourNetTests.cs
- src/Hero6.Tests/Engine/Utilities/Logger/LoggerTests.cs
- src/Hero6/Engine/Utilities/DependencyInjection/MonoGameServices.cs
- src/Hero6/Engine/Utilities/Logger/LogFourNet.cs
- src/Hero6/Engine/Utilities/Settings/UserSettings.Desktop.cs
- src/Hero6/Game.cs
Types will have instances made automatically. Only works on classes with empty constructors so far
> Restructured DI to add services by generics instead of instances

- scripts/azure-pipelines/nightly.yaml
- Nightly is separate yaml
- MacOS for PR is commented out
> Better azure yaml

- src/Hero6.Engine/ModuleController/Campaigns/Animations/MonoGameAnimationController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Animations/MonoGameCharacterAnimationController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Characters/MonoGameCharacterController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Characters/Stats/Hero6LearningStatController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Characters/Stats/Hero6StatController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Characters/Stats/MonoGameStatsController.cs
- src/Hero6.Engine/ModuleController/Campaigns/InventoryItems/MonoGameInventoryItemController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Items/MonoGameItemController.cs
- src/Hero6.Engine/ModuleController/Campaigns/MonoGameCampaignController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Rooms/MonoGameRoomController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Rooms/Regions/MonoGameHotspotsController.cs
- src/Hero6.Engine/ModuleController/Campaigns/Rooms/Regions/MonoGameWalkAreasController.cs
- src/Hero6.Engine/ModuleController/Controller.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/Components/MonoGameButtonController.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/Components/MonoGameImageController.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/Components/MonoGameLabelController.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/Components/MonoGameStackPanelController.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/Components/MonoGameWindowController.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/Input/Mouse/MonoGameCursorController.cs
- src/Hero6.Engine/ModuleController/UserInterfaces/MonoGameUserInterfaceController.cs
- src/Hero6.Engine/Services/Campaigns/MonoGameCampaigns.cs
- src/Hero6.Tests.HelperTools/ModuleController/Campaigns/Characters/CharacterTestBase.cs
- src/Hero6.Tests.HelperTools/ModuleController/Campaigns/Items/ItemTestBase.cs
- src/Hero6.Tests.HelperTools/ModuleController/Campaigns/Rooms/RoomTestBase.cs
- src/Hero6.Tests.HelperTools/ModuleController/ModuleControllerTestBase.cs
- src/Hero6.Tests.HelperTools/ModuleController/UserInterfaces/Components/WindowTestBase.cs
- src/Hero6.Tests.HelperTools/ModuleController/UserInterfaces/UserInterfaceTestBase.cs
- src/Hero6.UserInterfaces.SierraVga.Tests/Windows/StatusBarTests.cs
- src/Hero6.UserInterfaces.SierraVga.Tests/Windows/VerbBarTests.cs
We use the interface once, instead of many times
> Applied game loop pattern to root controller class.

- scripts/azure-pipelines/install.yaml
Azure pipelines keep changing their pipelines images git lfs configs so we have to install manually
> Added git lfs install step

- docs/BUILD-INSTRUCTIONS.md
- scripts/azure-pipelines/install.yaml
- src/.config/dotnet-tools.json
Instead of each individual developer having to install it manually
> Changed paket reference to be installed with dotnet tool restore

- scripts/azure-pipelines/bleeding.yaml
- scripts/azure-pipelines/nightly.yaml
Preparation work for upgrade to MonoGame 3.8, it has requirements that doesn't seem to exist on older versions of Ubuntu
> Updated Azure Ubuntu image to 18.04
