LateStartStudio/Hero6

src/AdventureGame/AdventureGame.csproj
src/Collections.Tests/Collections.Tests.csproj
src/Collections/Collections.csproj
src/Hero6.Android/Hero6.Android.csproj
src/Hero6.Android/Hero6.Android.csproj.DotSettings
src/Hero6.Campaigns.RitesOfPassage/Hero6.Campaigns.RitesOfPassage.csproj
src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
src/Hero6.UserInterface.SierraVGA/Hero6.UserInterface.SierraVGA.csproj
src/Hero6.WindowsDX/Hero6.WindowsDX.csproj
src/Search.Tests/Search.Tests.csproj
src/Search/Search.csproj

Set C# language version to "5.0" for all C# modules. Previously this was enforced by ReSharper, however I recently discovered that this could be enforced by a built in feature of the .NET compiler which is more handy. I also set language level for the Android module by ReSharper as it was missing

Set C# language version for all projects

---

.editorconfig
Hero6.sln
LICENSE.THIRDPARTY.md
README.md
src/Hero6.Installer.Windows/Data.wxi
src/Hero6.Installer.Windows/Hero6.Installer.Windows.wixproj
src/Hero6.Installer.Windows/Product.wxs

In reference to #1
Added a functional Windows installer for Hero6. The only thing missing as far as I can tell is pre-requisite software(.NET 4.5 and DirectX 9.0c), however everything else should be in place. It has a UI that allows user to choose install location, it installs a shortcut to the start menu, it allows upgrades and other things we would expect from an installer.
I suggest we just postpone the issue of installing pre-requisite software, the most important thing of this PR is that we have a stable and functional installer that we can build and expand further once integrated into our main branches.

Windows installer

---

src/AdventureGame/AdventureGame.csproj
src/Collections.Tests/Collections.Tests.csproj
src/Collections/Collections.csproj
src/Hero6.Android/Hero6.Android.csproj
src/Hero6.Campaigns.RitesOfPassage/Hero6.Campaigns.RitesOfPassage.csproj
src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
src/Hero6.Installer.Windows/Hero6.Installer.Windows.wixproj
src/Hero6.Tests/Hero6.Tests.shproj
src/Hero6.UserInterface.SierraVGA/Hero6.UserInterface.SierraVGA.csproj
src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj
src/Hero6.WindowsDX/Hero6.WindowsDX.csproj
src/Hero6/Hero6.shproj
src/Search.Tests/Search.Tests.csproj
src/Search/Search.csproj

Changed ToolsVersion into highest possible value that is supported on Linux builds. Most projects was set to 14, although highest version supported by Linux is 12. I also discovered that some projects had their ToolsVersion set to 4, which may be an artifact from when I have attempted to build on Linux in the past, and just set an arbitrary value.

Modified ToolsVersion

---

.editorconfig
.travis.yml
README.md
docs/LICENSE.THIRDPARTY.md
src/build.bat
src/build.fsx
src/build.sh
src/paket.dependencies
src/paket.lock

Like the title says I have adjusted the Travis config to include OS X and tweaked it so that it works on both Linux and OS X. During this ordeal I decied to add FAKE to the project, by using Common Language Interfacing I can gather all command line build scripts into a single place using batch and shell scripts only as native entry points.
FAKE is completely optional to use, it is helpful for low level CI servers like Travis which rely on scripts or terminal commands for building, but it can also be a useful tool for developers who want to work in text editors like Vim or Emacs instead of dedicated IDEs.

Added OS X build to Travis and FAKE build scripts

---

src/AdventureGame/Campaign.cs
src/AdventureGame/Engine/Engine.cs
src/AdventureGame/UI/UserInterface.cs
src/Hero6.UserInterface.SierraVga/SierraVgaController.cs
src/Hero6.UserInterface.SierraVga/ViewModel/TextBoxViewModel.cs

Like title says.
One way of testing this is to make the hero move from point A to point B, and while he's moving, make a UI element like the Verb bar show, the hero should then stop, when the UI is hidden again he should resume movement.

Pause game on rendering UI elements like Message Box and Verb Bar

---

src/Hero6.UserInterface.SierraVga/MouseCursor.cs

Had to add switch case for CursorType.None since this was used in unit tests and caused the tests to fail.

Added switch case for CursorType.None.

---

src/Hero6/Game.cs
src/Hero6/Hero6.projitems
src/Hero6/Utilities/DummyLogger.cs
src/Hero6/Utilities/LogFourNet.cs

Android platform wouldn't compile because of missing reference to log4net, which wouldn't install by nuget, presumably becaue log4net doesn't offer package for monoandroid??? Either way I don't want to spend more energy than needed working on a platform we may or may not support so I just made a dummy switch to remove log4net references.

#84 Made dummy placeholder logger class for Android platform

---

src/Hero6.UserInterface.SierraVga/ViewModel/TextBoxViewModel.cs

EmptyKeys doesn't seem to able to perfectly measure string, add another pixel for safe measure. It's kinda hacky, but as far as hacks go this a pretty safe one.

#92 Fixed size alloction for text boxes

---

src/Hero6.UserInterface.SierraVga.Xaml/Hero6.UserInterface.SierraVga.Xaml.csproj

Most paths in the Xaml module SierraVga had become invalid after a re organization of asset directories, this should now be fixed.

Sierra VGA directory fix

---

src/build.fsx

FAKE built Hero6 in a location where Advanced Installer couldn't reach it.

#102 Changed build path for FAKE script

---

src/Hero6.Installer.Windows/Hero6.Installer.Windows.aip

I modified the windows installer so it would organize binaries in a folder "bin" and our text docs like licensing into a "docs" folder.
I added the .xml documentation files of various assemblies.
I set the installer version to reference the assembly version.

Installer Cleanup

---

src/AdventureGame/AdventureGame.csproj
src/Collections.Tests/Collections.Tests.csproj
src/Collections/Collections.csproj
src/Hero6.Android/Hero6.Android.csproj
src/Hero6.Campaigns.RitesOfPassage/Hero6.Campaigns.RitesOfPassage.csproj
src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
src/Hero6.DesktopGL/Hero6.DesktopGL.csproj
src/Hero6.UserInterface.SierraVga.Xaml/Hero6.UserInterface.SierraVga.Xaml.csproj
src/Hero6.UserInterface.SierraVga/Hero6.UserInterface.SierraVga.csproj
src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj
src/Hero6.WindowsDX/Hero6.WindowsDX.csproj
src/Search.Tests/Search.Tests.csproj
src/Search/Search.csproj

I set the .csproj property "Treat warnings as errors" to true, for most open-source projects I've seen this is standard practice. The perk to this is obvious, avoid warnings sneaking in on pull requests and have them stacking up on us. It can make coding a little more tedious I guess but in my experience this is not a problem.

Treat Warnings as errors

---

assets/Hero6.Content.mgcb

I set the MonoGame Content Pipeline Tool to compress the assets on pre-processing. This should result in that the finished product takes significantly less space on disk and possibly memory, on the expense of increased loading time. Although any increased loading time is unlikely to be noticeable on such an old retro style game like this.
Size of Content folder
Before: 2.56 MB
After: 738 KB

Compressed Assets

---

src/AdventureGame.Tests/AdventureGame.Tests.csproj
src/AdventureGame.Tests/DummyTests.cs
src/AdventureGame.Tests/Engine/MockContentManager.cs
src/AdventureGame.Tests/Engine/MockEngine.cs
src/AdventureGame.Tests/MockCampaign.cs
src/AdventureGame.Tests/UI/MockUserInterface.cs
src/Collections.Tests/Collections.Tests.csproj
src/Collections.Tests/Generic/BlueRajaWrapperTests.cs
src/Collections.Tests/Generic/Node.cs
src/Collections.Tests/Generic/PriorityQueueTests.cs
src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
src/Hero6.Tests/GameTests.cs
src/Hero6.Tests/Hero6.Tests.projitems
src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj
src/Search.Tests/Pathfinder/AStarTests.cs
src/Search.Tests/Pathfinder/DijkstraTests.cs
src/Search.Tests/Pathfinder/NodeTests.cs
src/Search.Tests/Pathfinder/PathfinderTests.cs
src/Search.Tests/Search.Tests.csproj

Removed the "Test" from unit test namespaces as it was plain simpler to reference classes from the same namespace they came from. It was also necessary in the case of shared code that the test project and original projects share the same namespace as code generators would get confused.

Simplify unit test projects namespaces

---

.appveyor.yml
src/Hero6.Tests/GameTests.cs
src/build.fsx

I removed some unit tests that relied on GPU hardware to initialize. I should never have made these unit tests in the first place, but I fell for the temptation of having tests that checks if the game actually starts. In reality however we had to make ugly special cases for the main game test assembly so it wouldn't run tests on systems missing GPUs, and the tests was to expensive perfomance wise to be integrated into development patterns like TTD or any form where unit tests should be run often.

Removed unconventional unit tests

---

src/build.fsx

We do not support or maintain it as stated in the readme

Disabled Android builds from the FAKE script

---

src/Hero6.Engine.Tests/UserInterfaces/MockUserInterface.cs
src/Hero6.Engine.UserInterfaces.SierraVga/MouseCursor.cs
src/Hero6.Engine.UserInterfaces.SierraVga/SierraVgaController.cs
src/Hero6.Engine/Campaigns/AdventureGameElement.cs
src/Hero6.Engine/Campaigns/Campaign.cs
src/Hero6.Engine/Campaigns/Character.cs
src/Hero6.Engine/Campaigns/CharacterAnimation.cs
src/Hero6.Engine/Campaigns/InventoryItem.cs
src/Hero6.Engine/Campaigns/Item.cs
src/Hero6.Engine/Campaigns/Room.cs
src/Hero6.Engine/Campaigns/SpriteSheet.cs
src/Hero6.Engine/GameLoop/DrawEventArgs.cs
src/Hero6.Engine/GameLoop/IGameLoop.cs
src/Hero6.Engine/GameLoop/UpdateEventArgs.cs
src/Hero6.Engine/UserInterfaces/UserInterface.cs
src/Hero6/Engine/Campaigns/CampaignHandler.cs
src/Hero6/Engine/UserInterfaces/UserInterfaceHandler.cs
src/Hero6/Game.cs
src/Hero6/IXnaGameLoop.cs

This fixes a small annoyance I've had for a long time with the Update and Draw function calls. The line with the function name and arguments is so long I end up breaking it over multiple lines, however by simplifying some of the argument names(removing time from gameTime argument name) I can put the Update and Draw function to a single line, which is much nicer.

Simplify Update and Draw argument list

---

src/Hero6.Engine.Tests/Hero6.Engine.Tests.csproj
src/Hero6.Engine/Campaigns/PlayerCharacter.cs
src/Hero6.Engine/Campaigns/Stats/Stat.cs
src/Hero6.Engine/Campaigns/Stats/StatChangedEventArgs.cs
src/Hero6.NoDocumentation.ruleset
src/Hero6.ruleset
src/Search.Tests/Pathfinder/PathfinderTests.cs

I don't remember what reasons we had for demoting this rule into a "Info" but I'm going to veto this and set it back to a Warning check. The Info is not satisfactory for this as it only triggers when the actual code file is open in the editor, and we do not want trailing white spaces.

Set rule SA1028 to warning, code must not containt trailing whitespaces

---

.appveyor.yml
.travis.yml
src/.ci/Readme.md
src/.ci/before_install.linux.sh
src/.ci/before_install.osx.sh
src/.ci/before_script.linux.sh
src/.ci/before_script.osx.sh
src/.ci/install.linux.sh
src/.ci/install.osx.sh
src/.ci/install.ps1
src/.ci/script.linux.sh
src/.ci/script.osx.sh
src/build.bat
src/build.sh
src/paket.bat
src/paket.sh

- Cleaned up Travis build steps by adding each step in separate scripts, invoking platform specific script by environment variable.
- Cleaned up Appveyor script by moving install step to Powershell script.
- Moved paket package restoration to a separate script
- Paket script will now only run bootstrapper if paket.exe doesn't already exist

Organized build scripts

---

src/Hero6.Engine.Campaigns.RitesOfPassage/Hero6.Engine.Campaigns.RitesOfPassage.csproj

It had a x86 platform, however there's no reason for it to have that so it was replaced with AnyCPU

Changed campaign module platform

---

src/build.fsx

Fixed some errors in the FAKE build script. Certain dependencies assumed that all the built files ended in a standard "bin" folder for each project, rather than a single custom chosen path which was the case with our FAKE script. This is now fixed so that it goes with the former option, rather than the latter, the reason this problem was introduced was a misunderstanding in how the FAKE MsBuild command worked, as the first string it takes as a forced input argument is the build dir, however as it turns out it is completely legal to pass a empty string and it will then defer to standard behavior

Fix FAKE script

---

src/Hero6.Engine/Campaigns/CharacterAnimation.cs
src/Hero6/Engine/Campaigns/CampaignHandler.cs

In the campaign handler the total and elapsed timespan arguments was switched which resulted in head scratching debugging whenever I have to work with frame independent logic.

Fixed wrong insertion of TimeSpan arguments

---

src/Hero6.Engine.Campaigns.RitesOfPassage/RitesOfPassage.cs
src/Hero6.Engine.Tests/Campaigns/MockCampaign.cs
src/Hero6.Engine.Tests/GameLoop/DrawEventArgsTests.cs
src/Hero6.Engine/Campaigns/Campaign.cs
src/Hero6.Engine/Campaigns/CharacterAnimation.cs
src/Hero6.Engine/Campaigns/Room.cs
src/Hero6/Engine/Campaigns/CampaignHandler.cs

The similar property was already static in UserInterface.cs and Game.cs, but it wasn't changed in Campaign.cs for legacy reasons.

Changed renderer property in Campaign to static

---

src/build.fsx

Somehow when I earlier fixed the unit testing I neglected to verify that it also worked on *nix systems. I made the script throw an exception to make sure that we're running unit tests on any system

Fixed unit tests FAKE build

---

.gitignore
src/Hero6/Game.cs

I want people to be able to store the Hero6 source code in their Documents folder without it conflicting with the git diff

Renamed logs folder and added it to gitignore

---

src/Hero6.DesktopGL.Tests/Hero6.DesktopGL.Tests.csproj
src/Hero6.Tests/GameTests.DesktopGL.cs
src/Hero6.Tests/GameTests.WindowsDX.cs
src/Hero6.Tests/Hero6.Tests.projitems
src/Hero6.Windows.sln
src/Hero6.WindowsDX.Tests/GameTests.WindowsDX.cs
src/Hero6.WindowsDX.Tests/Hero6.WindowsDX.Tests.csproj

- Added simple tests for GraphicsAPI string get
- Changed assembly name
- Both platform test projects is set to build not matter which solution config is selected. We can't involve hardware specific stuff in unit tests so it should be non-controversial

Changed Hero6 unit tests

---

src/Hero6.Engine.Tests/Services/DependencyInjection/ServiceLocatorTests.cs
src/Hero6.Engine/Hero6.Engine.projitems
src/Hero6.Engine/ModuleController/Controller.cs
src/Hero6.Engine/Services/DependencyInjection/IgnoreAttribute.cs
src/Hero6.Engine/Services/DependencyInjection/MonoGameServiceLocator.cs

So that it is contained within the dependency injection namespace instead of inside a generic attributes namespace

Refactored ignore attribute
